// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscriber struct {
	Msisdn       int64
	UpdatedAt    pgtype.Timestamp
	BillingType  int16
	LanguageType int16
	OperatorType int16
}
