// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package database

import (
	"context"
)

const getSubscriber = `-- name: GetSubscriber :one
select
	msisdn,
	updated_at,
	billing_type,
	language_type,
	operator_type
from subscribers
where msisdn = $1
`

func (q *Queries) GetSubscriber(ctx context.Context, msisdn int64) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriber, msisdn)
	var i Subscriber
	err := row.Scan(
		&i.Msisdn,
		&i.UpdatedAt,
		&i.BillingType,
		&i.LanguageType,
		&i.OperatorType,
	)
	return i, err
}

const updateSubscriber = `-- name: UpdateSubscriber :exec
insert into subscribers (
	msisdn,
	billing_type,
	language_type,
	operator_type
)
values (
	$1,
	$2,
	$3,
	$4
)
on conflict (msisdn) do update
set
	updated_at = now(),
	billing_type = excluded.billing_type,
	language_type = excluded.language_type,
	operator_type = excluded.operator_type
`

type UpdateSubscriberParams struct {
	Msisdn       int64
	BillingType  int16
	LanguageType int16
	OperatorType int16
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) error {
	_, err := q.db.Exec(ctx, updateSubscriber,
		arg.Msisdn,
		arg.BillingType,
		arg.LanguageType,
		arg.OperatorType,
	)
	return err
}
